---
- name: add groups {{ add_user_groups }}
  become: true
  group:
    name: "{{ item }}"
  with_items: "{{ add_user_groups }}"

- name: add user {{ add_user_name }}
  become: true
  user:
    name: "{{ add_user_name }}"
    groups: "{{ add_user_groups }}"
    shell: /bin/bash
  when: add_user_password is not defined

# Note: In order to avoid a changed state when setting the password
# it needs to be set when the user is created.
- name: add user {{ add_user_name }} with password
  become: true
  user:
    name: "{{ add_user_name }}"
    groups: "{{ add_user_groups }}"
    shell: /bin/bash
    # string filter is workaround for ansible vault issue
    # https://github.com/ansible/ansible/pull/35406
    password: "{{ add_user_password | string | password_hash('sha512') }}"
    update_password: on_create
  when: add_user_password is defined

- name: enable passwordless sudo for group {{ add_user_name }}
  become: true
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%{{ add_user_name }}'
    line: '%{{ add_user_name }} ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  when: add_user_passwordless_sudo

- name: add ssh key
  become: true
  authorized_key:
    user: "{{ add_user_name }}"
    key: "{{ add_user_public_key }}"
  when: add_user_public_key is defined
